from flask import Flask, request, jsonify, send_from_directory, send_file
from flask_cors import CORS
from flask_jwt_extended import JWTManager, create_access_token, jwt_required, get_jwt_identity
from werkzeug.security import generate_password_hash, check_password_hash
import sqlite3
import os
from faster_whisper import WhisperModel
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit
import uuid
import gc

app = Flask(__name__)
CORS(app)
app.config['JWT_SECRET_KEY'] = 'super-secret-key-change-in-production-2026'
jwt = JWTManager(app)

whisper_model = WhisperModel("tiny", device="cpu", compute_type="int8")

UPLOAD_FOLDER = "uploads"
PDF_FOLDER = "pdfs"
MIDI_FOLDER = "midi"

for folder in [UPLOAD_FOLDER, PDF_FOLDER, MIDI_FOLDER]:
    os.makedirs(folder, exist_ok=True)

# SQLite setup
def get_db():
    conn = sqlite3.connect('chordscribe.db')
    conn.row_factory = sqlite3.Row
    return conn

with get_db() as conn:
    conn.execute('''CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL,
        credits INTEGER DEFAULT 5,
        optin INTEGER DEFAULT 1
    )''')

@app.route('/')
def home():
    return send_from_directory('.', 'index.html')

@app.route('/api/register', methods=['POST'])
def register():
    data = request.get_json()
    email = data.get('email')
    password = data.get('password')
    optin = data.get('optin', True)
    
    if not email or not password:
        return jsonify({"success": False, "error": "Email and password required"}), 400
    
    hashed = generate_password_hash(password)
    
    try:
        with get_db() as conn:
            conn.execute("INSERT INTO users (email, password, credits, optin) VALUES (?, ?, 5, ?)", 
                        (email, hashed, 1 if optin else 0))
            conn.commit()
        return jsonify({"success": True, "message": "Account created successfully"})
    except Exception:
        return jsonify({"success": False, "error": "Email already exists"}), 400

@app.route('/api/login', methods=['POST'])
def login():
    data = request.get_json()
    email = data.get('email')
    password = data.get('password')
    
    with get_db() as conn:
        user = conn.execute("SELECT * FROM users WHERE email = ?", (email,)).fetchone()
    
    if user and check_password_hash(user['password'], password):
        access_token = create_access_token(identity=str(user['id']))
        return jsonify({
            "success": True, 
            "token": access_token, 
            "email": email,
            "credits": user['credits']
        })
    
    return jsonify({"success": False, "error": "Invalid credentials"}), 401

@app.route('/api/transcribe', methods=['POST'])
@jwt_required()
def transcribe():
    if 'file' not in request.files:
        return jsonify({"success": False, "error": "No file uploaded"}), 400
    
    file = request.files['file']
    if file.filename == '':
        return jsonify({"success": False, "error": "No selected file"}), 400
    
    filename = str(uuid.uuid4()) + "_" + file.filename
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    file.save(filepath)
    
    try:
        segments, info = whisper_model.transcribe(
            filepath, 
            beam_size=5, 
            language="en", 
            vad_filter=False
        )
        
        lyrics = "\n".join([segment.text.strip() for segment in segments if segment.text.strip()])
        if not lyrics:
            lyrics = "No clear vocals detected in this audio."

        pdf_filename = f"{uuid.uuid4()}.pdf"
        pdf_path = os.path.join(PDF_FOLDER, pdf_filename)
        generate_pdf(pdf_path, file.filename, lyrics)

        midi_filename = f"{uuid.uuid4()}.mid"
        midi_path = os.path.join(MIDI_FOLDER, midi_filename)
        generate_simple_midi(midi_path)

        if os.path.exists(filepath):
            os.remove(filepath)
        gc.collect()

        return jsonify({
            "success": True,
            "lyrics": lyrics,
            "pdf_filename": pdf_filename,
            "midi_filename": midi_filename
        })
        
    except Exception as e:
        if os.path.exists(filepath):
            os.remove(filepath)
        gc.collect()
        return jsonify({"success": False, "error": str(e)}), 500

def generate_pdf(pdf_path, song_name, lyrics):
    c = canvas.Canvas(pdf_path, pagesize=letter)
    width, height = letter
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 80, "Chordscribe")
    c.setFont("Helvetica", 18)
    c.drawString(50, height - 120, f"Song: {song_name}")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 150, "Generated by Chordscribe")

    y = height - 200
    common_chords = ["C", "Am", "F", "G", "Em", "Dm"]
    chord_idx = 0
    lines = lyrics.split('\n')
    for line in lines:
        if not line.strip():
            y -= 20
            continue
        chord = common_chords[chord_idx % len(common_chords)]
        c.drawString(70, y, f"[{chord}]")
        c.setFont("Helvetica", 12)
        wrapped = simpleSplit(line.strip(), "Helvetica", 12, 450)
        for wline in wrapped:
            c.drawString(140, y, wline)
            y -= 18
        chord_idx += 1
        y -= 15
        if y < 100:
            c.showPage()
            y = height - 
